version: "3"
services:
  mongo:
    image: mongo
    container_name: hospital_mongo
    ports:
      - "27017:27017"
    restart: always

  app:
    build: .
    container_name: hospital_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/hospital